### ISSUE TITLE
Centos 7

### ISSUE THREAD

**Issue by univ3338** [zzet/elasticsearch-git#9]
Trying to install on Centos 7 and getting following error:

extconf.rb:7:in `sys': patch -p0 < ../file-soft-check.patch failed, please report issue on http://github.com/brianmario/charlock_holmes (RuntimeError)
    from extconf.rb:61:in`block (2 levels) in <main>'
    from extconf.rb:59:in `chdir'
    from extconf.rb:59:in`block in <main>'
    from extconf.rb:55:in `chdir'
    from extconf.rb:55:in`<main>'

Any pointers?

**Comment by zzet** [comment]
@univ3338 :+1:  :)
